# WARNING - Generated by {fusen} from /dev/flat_minimal.Rmd: do not edit by hand

test_that("test uj_matx", {
  
  mat_test <- matrix(c(100, 90, 80, 70, 60, 50,
                       90, 80, 70, 60, 50, 40,
                       80, 70, 60, 50, 40, 30,
                       70, 60, 50, 40, 30, 20,
                       60, 50, 40, 30, 20, 10,
                       50, 40, 30, 20, 10, 0),
                     nrow = 6,
                     byrow = T)
  
  expect_equal(uj_matx(max.val = 100, ratio.util = 0.1, ratio.just = 0.1),
               mat_test)
  
  expect_error(uj_matx(max.val = 0))
  expect_error(uj_matx(max.val = 'A'))
  
  expect_error(uj_matx(ratio.util = 0.6))
  expect_error(uj_matx(ratio.util = 0))
  
  expect_error(uj_matx(just.util = 0.6))
  expect_error(uj_matx(just.util = 0))
  
})
