# WARNING - Generated by {fusen} from /dev/flat_minimal.Rmd: do not edit by hand

#' Utility - Justice matrix
#'
#' @description Creates a matrix with scores for utility and justice criteria on organ transplantation
#' @param max.val A numerical value corresponding o the matrix maximum value. 
#' @param ratio.util A numerical value between 0 and 0.5 corresponding to the decreasing rate for the utility criterion (by column)
#' @param ratio.just A numerical value between 0 and 0.5 corresponding to the decreasing rate for the justice criterion (by column)
#' @return A 6 by 6 matrix with at line 1 row 1 has the maximum value and at line 6, row 6 has it's minimum.
#' @export
#' @examples
#' \dontrun{
#' uj_matx_v0(max.val = 100, ratio.util = 0.1, ratio.just = 0.1)
#' }
uj_matx_v0 <- function(max.val = 100,
                    ratio.util = 0.1,
                    ratio.just = 0.1){
  
  if(!(ratio.just > 0 & ratio.just < 0.5 & 
       ratio.util > 0 & ratio.util < 0.5)
     ){stop('ratio values are not between 0 and 0.5!')}
  
  if(!(max.val > 0)){stop('max.val is not greater than 0!')} 
  
  matx <- matrix(nrow = 6,
                 ncol = 6)
  # rownames(matx) <- c('a','b','c','d','e','f')
  # colnames(matx) <- c('a','b','c','d','e','f')
  
  util.val <- max.val * ratio.util
  just.val <- max.val * ratio.just
  
  l1 <- max.val
  for(i in 1:5){l1 <- c(l1,max.val - util.val*i)}
  c1 <- max.val
  for(i in 1:5){c1 <- c(c1,max.val - just.val*i)}
  
  matx[1,] <- l1
  matx[,1] <- c1 
  
  for(i in 2:6){
    for(j in 2:6){
      matx[i,j] <- matx[i, j-1] - util.val
      }
  }
  
  if( is.na(sum(matx)) | is.nan(sum(matx)) ){stop("The matrix have non valid numbers!")}

  matx0 <- matrix(0, ncol = 6, nrow = 6)
  # rownames(matx0) <- c('a','b','c','d','e','f')
  # colnames(matx0) <- c('a','b','c','d','e','f')
  if(identical(matx,matx0) ){stop("All matrix values are zeros!")}
  
  return(matx)
}
